server:
  port: 8090

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:devData;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${spring.datasource.url}
    user: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---

spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:prodData;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${spring.datasource.url}
    user: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

